name: ESP32 + Bluepad32 Build

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile Arduino sketch
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32_bluepad32:esp32
              source-url: https://raw.githubusercontent.com/ricardoquesada/esp32-arduino-lib-builder/bluepad32/package_esp32_bluepad32_index.json
          fqbn: esp32_bluepad32:esp32:esp32s3
          sketch-paths: |
            AutonomousRC
